config/routes.rb
ContactForm::Application.routes.draw do
  resources :inquiries, only: [:create, :index, :new, :show, :destroy]
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates_presence_of :email, :subject, :description, :firstname, :lastname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params.require(:inquiry).permit(:email, :subject, :description, :firstname, :lastname))
    if @inquiry.save
      redirect_to @inquiry, notice: 'Inquiry was successfully created.'
    else
      render action: 'new'
    end
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def index
    @inquiries = Inquiry.all
  end

  def destroy
    Inquiry.find(params[:id]).destroy
    redirect_to inquiries_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inquiries/index.html.erb
<h1>Inquiries List</h1>
<%= link_to 'Create New', new_inquiry_path %>
<ol>
<% @inquiries.each do |inquiry| %>
  <div style="float: left"><li><%= link_to inquiry.subject, inquiry %> <%= ' | ' + inquiry.firstname + ' ' + inquiry.lastname  + ' (' + inquiry.email + ') '%></div><%= button_to "Delete", { action: "destroy", id: inquiry.id }, method: :delete, data: { confirm: "Are you sure?" } %></li>
<% end %>
</ol>

app/views/inquiries/new.html.erb
<h1>New Contact Inquiry</h1>

<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <p>Error(s) detected; inquiry not saved.</p>
  <% end %>
    <div>
      <%= f.label :email %>:
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :subject %>:
      <%= f.text_field :subject %>
    </div>
    <div>
      <%= f.label :description %>:
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :firstname %>:
      <%= f.text_field :firstname %>
    </div>
      <div>
      <%= f.label :lastname %>:
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/inquiries/show.html.erb
<h1>Contact Inquiry</h1>
<p id="notice"><%= notice %></p>
<p><%= @inquiry.email %></p>
<p><%= @inquiry.subject %></p>
<p><%= @inquiry.description %></p>
<p><%= @inquiry.firstname %> <%= @inquiry.lastname %></p>
<%= link_to 'Back To Index', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>